name: Build Rust Project

on:
  workflow_dispatch:  # 手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # 更新到最新版本

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Build Server
      run: cargo build --release --package cli --bin server

    - name: Build Client
      run: cargo build --release --package cli --bin client

    - name: Archive Server Artifact
      uses: actions/upload-artifact@v3  # 使用最新版本
      with:
        name: server-executable
        path: target/release/server  # 根据实际可执行文件名调整

    - name: Archive Client Artifact
      uses: actions/upload-artifact@v3  # 使用最新版本
      with:
        name: client-executable
        path: target/release/client  # 根据实际可执行文件名调整
