name: Build Rust Project

on:
  workflow_dispatch:  # 手动触发

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        target: [x86_64-unknown-linux-gnu, x86_64-pc-windows-msvc]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Build
      run: |
        if [[ ${{ matrix.os }} == 'ubuntu-latest' ]]; then
          cargo build --release --package cli --bin server --target x86_64-unknown-linux-gnu
          cargo build --release --package cli --bin client --target x86_64-unknown-linux-gnu
        else
          cargo build --release --package cli --bin server --target x86_64-pc-windows-msvc
          cargo build --release --package cli --bin client --target x86_64-pc-windows-msvc
        fi

    - name: Archive Server Artifact
      uses: actions/upload-artifact@v3
      with:
        name: server-${{ matrix.os }}
        path: target/release/server${{ matrix.os == 'windows-latest' && '.exe' || '' }}

    - name: Archive Client Artifact
      uses: actions/upload-artifact@v3
      with:
        name: client-${{ matrix.os }}
        path: target/release/client${{ matrix.os == 'windows-latest' && '.exe' || '' }}
